spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200
  main:
    allow-circular-references: true
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        slf4j:
          enabled: true # 开启日志功能
        wall:
          enabled: true # 开启防火墙功能
        stat:
          enabled: true # 开启sql监控功能
          slow-sql-millis: 1000  # 配置SQL慢的标准
          log-slow-sql: true # 是否开启记录执行慢的sql
      stat-view-servlet:
        enabled: true # 开启监控页功能
        login-username: root # 监控页登录账号
        login-password: root # 监控页登录密码
        reset-enable: false # 配置是否允许重置监控信息
      web-stat-filter:
        enabled: true # 开启web监控
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # web监控白名单
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB

# 日志
logging:
  pattern: console:%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
  level:
    space.rexhub.kbms.bussiness.dao: debug

